const productColourPop = () => {
    var store = 'colourpop';
    var available = true;
    var width = null;
    var isImageAvailable = null;
    var priceStr = $('.product-details__right .product-details__price--sale').clone().children().remove().end().text();
    priceStr = priceStr.replace(',', '');
    console.log('priceStr>>>>>>>>>', priceStr);
    var regex = /[+-]?\d+(\.\d+)?/g;
    var price = priceStr.match(regex)[0];
    console.log('price>>>>>', price);
    var currencySymbol = priceStr.replace(price, '');
    currencySymbol = currencySymbol.replace('USD', '');
    currencySymbol = currencySymbol.trim();
    console.log('currencySymbol-colourpop>>>>>>', currencySymbol);
    var title = $('.showtablet .product-details__title').text();
    title = title.replace("'", '');
    var sizeExist = $('input[name=size-options]').attr('value');
    var sizeTemp = $('input[name=size-options]:checked').attr('value');
    var size = sizeExist ? ((sizeTemp) ? sizeTemp : 'select') : '';
    console.log('size>>>>>>', size);
    var colorExist = $('.selectedColor').text();
    var color = colorExist ? ($('.selectedColor').text()) : null;
    var imageUrl = $('.product-images__carousel .product-image img').attr('src');
    imageUrl =  'https:' + imageUrl;
    imageUrl = imageUrl.split('?')[0];
    var count = $('.product-actions__quantity--input').val() || 1;
    price = price * count;

    return {currencySymbol, price,  title, imageUrl, color, size, count, available, store, width, isImageAvailable};
};
