const productCosmetics = () => {
    var store = 'comsetics';
    var available = true;
    var width = null;
    var isImageAvailable = null;
    var priceStr = $('.product-price').text();
    priceStr = priceStr.replace(',', '');
    console.log('priceStr>>>>>>>>>', priceStr);
    var regex = /[+-]?\d+(\.\d+)?/g;
    var price = priceStr.match(regex)[0];
    console.log('price>>>>>>.', price);
    let currencySymbol = priceStr.replace(',', '');
    currencySymbol = currencySymbol.replace(price, '');
    currencySymbol = currencySymbol.replace('USD', '');
    currencySymbol = currencySymbol.trim();
    console.log('currencySymbol-cosmetics>>>>>>', currencySymbol);
    var title = $('.section-title h1').text();
    title = title.replace("'", '');
    var sizeExist = $('input[name=size-options]').attr('value');
    var sizeTemp = $('input[name=size-options]:checked').attr('value');
    var size = sizeExist ? ((sizeTemp) ? sizeTemp : 'select') : '';
    console.log('size>>>>>>', size);
    var colorExist = $('.selectedColor').text();
    var color = colorExist ? ($('.selectedColor').text()) : null;
    var imageUrl = $('#thumbnail-gallery img').attr('src');
    imageUrl =  'https:' + imageUrl;
    imageUrl = imageUrl.split('?')[0];
    var count = $('input[name=quantity]').val() || 1;
    price = price * count;

    return {currencySymbol, price,  title, imageUrl, color, size, count, available, store, width, isImageAvailable};
};
