const productModaoperandi = () => {
    var store = 'modaoperandi';
    var available = true;
    var priceStr = $('.pdp_description_wrapper .current_price').text();
    priceStr = priceStr.replace(',', '');
    console.log('priceStr>>>>>>', priceStr);
    var regex = /[+-]?\d+(\.\d+)?/g;
    var price = priceStr.match(regex)[0];
    console.log('price>>>>>', price);
    var currencySymbol = priceStr.replace(price, '');
    currencySymbol = currencySymbol.replace('USD', '');
    currencySymbol = currencySymbol.trim();
    console.log('currencySymbol-Revolve>>>>>>', currencySymbol);
    var title = $('.product_description .product_title').text();
    title = title.replace("'", '');
    var size = null;
    var color = null;
    var width = null;
    var sizeExist = $('.select_size_message').text();
    size = $('.select_size_message').clone().children().remove().end().text().replace('—','');
    size = sizeExist.includes('select') ? 'select' : size;
    console.log('size>>>>>>', size);
    console.log('width>>>>>>', width);
    console.log('color>>>>>>', color);
    var imageUrl = $('#current_image_display img').attr('src');
    imageUrl = imageUrl.slice(0, imageUrl.indexOf('?'));
    var count = 1;
    console.log('imageUrl>>>>>', imageUrl);
    console.log('count>>>>>', count);
    var isImageAvailable = null;

    return {currencySymbol, price,  title, imageUrl, color, size, count, available, store, width, isImageAvailable};
};
